controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
      command_interfaces: 
        - position 
      state_interfaces: 
        - position 
        - velocity
      state_publish_rate: 50 
      action_monitor_rate: 20