controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4 
        - joint5
        - joint6
